import {
  Award,
  BadgeCheck,
  BarChart3,
  Boxes,
  BrainCircuit,
  Briefcase,
  Building2,
  CalendarClock,
  Cloud,
  Cpu,
  Database,
  Flag,
  Globe,
  Globe2,
  HandHeart,
  Handshake,
  Hammer,
  HeartPulse,
  Landmark,
  LayoutDashboard,
  LayoutGrid,
  Lightbulb,
  LineChart,
  Link2,
  MapPin,
  Receipt,
  Rocket,
  Scaling,
  Share2,
  ShieldCheck,
  ShoppingBasket,
  Shuffle,
  Sparkles,
  Star,
  Stethoscope,
  Store,
  TrendingUp,
  UserPlus,
  Users,
  Users2,
  Workflow,
  type LucideIcon,
} from "lucide-react";
import { cn } from "@/lib/utils";

const registry: Record<string, LucideIcon> = {
  Award,
  BadgeCheck,
  BarChart3,
  Boxes,
  BrainCircuit,
  Briefcase,
  Building2,
  CalendarClock,
  Cloud,
  Cpu,
  Database,
  Flag,
  Globe,
  Globe2,
  HandHeart,
  Handshake,
  Hammer,
  HeartPulse,
  Landmark,
  LayoutDashboard,
  LayoutGrid,
  Lightbulb,
  LineChart,
  Link2,
  MapPin,
  Receipt,
  Rocket,
  Scaling,
  Share2,
  ShieldCheck,
  ShoppingBasket,
  Shuffle,
  Sparkles,
  Star,
  Stethoscope,
  Store,
  TrendingUp,
  UserPlus,
  Users,
  Users2,
  Workflow,
};

type IconProps = {
  name: string;
  className?: string;
  strokeWidth?: number;
};

/** Resolve a string key from content.ts to a lucide icon. Falls back to Sparkles. */
export function Icon({ name, className, strokeWidth = 1.75 }: IconProps) {
  const Cmp = registry[name] ?? Sparkles;
  return <Cmp className={cn("h-6 w-6", className)} strokeWidth={strokeWidth} aria-hidden />;
}
